### ISSUE TITLE
Bug: players at the button of the page not clickable

### ISSUE THREAD

**Issue by mojoaxel** [beatboxjs/ror-player#45]
It can happen, that some player-buttons on the button of the page are not clickable, because they are covered by a (invisible) element:

![image](https://github.com/beatboxjs/ror-player/assets/600565/b88797ad-dc5d-475c-ba6d-bda728d45c29)

Tho fix this the element "bb-update" should be hidden if the content (alert) is not visible.

**Comment by poedelina** [comment]
I am a nitwit. How do you do that? Since I don't see the element and there is no box to click on....

**Comment by cdauth** [comment]
Thanks for the report, this should be fixed now!
