### ISSUE TITLE
Problem playing previously created tune

### ISSUE THREAD

**Issue by LeonardoCaisachanaGuevara** [beatboxjs/ror-player#46]
Hi,

I created a tune a couple of years ago and I used to play it always using the link provided by the ROR player.
Now, after clicking the link as usual an error comes up that is not solved by switching navigators or devices:
Error importing Tune (Hola): [ { "code": "invalid_type", "expected": "number", "received": "string", "path": [ "time" ], "message": "Expected number, received string" } ]

My group and I would really like to show this tune at the coming TNM in Berlin so I hope you can help us!

Thank you very much in advance,
Leonardo

**Comment by cdauth** [comment]
Thanks for the report, could you share the link?

**Comment by LeonardoCaisachanaGuevara** [comment]
Maybe, if there was an update, a previous version of the player could play it and then I could rewrite it in the new version?
The problem is that I would lose the tune if it can't be fixed as I don't remember it by heart.
Thanks again for the help!

**Comment by LeonardoCaisachanaGuevara** [comment]
Yes the link is: 

https://player.rhythms-of-resistance.org/#/compose/TU7LCsJADPyVzdoqWK34QMWTRz_Aw1z3UK3Qh6TrqfjvTloRd_JYZjIhvX-GGAttOn_q_aWtgvXrqymsV2S9TARLwXoKRxxF_cLXo5CQyKxsEwDky4FPBZlgk-I3r1znHf3f0JsrCSUGX9dQBzTPQYxhRVUHPQbTHb2j_69TDXeqrbaBqa5lqhVjNNj2kvo5BhHMBHPBitcJDjKsftR23J7fqmjukbO7N98H/Hola/Tune

**Comment by cdauth** [comment]
The link should work now. You need to reload the player to load the new version.

**Comment by LeonardoCaisachanaGuevara** [comment]
Thank you very much. I greatly appreciate it!
